### ISSUE TITLE
HTML5 form types not supported?

### ISSUE THREAD

**Issue by matthew-dean** [caolan/forms#133]
I notice that the toHTML() function generates "required" wrappers and other types rather than generating html like:

```
<input type="text" required />
```
or
```
<input type="url" />
```
Is support for basic html5 form types coming?

**Comment by vekexasia** [comment]
@ljharb how should i enable the html5 required attribute?

**Comment by ljharb** [comment]
You should be able to set it manually by simply passing `required` set to `true`, in the attributes passed to a widget.

**Comment by niallobrien** [comment]
I think browser support has greatly improved since this issue was last discussed.

**Comment by ljharb** [comment]
@niallobrien not in my experience :-/ note that "browser support" includes "most sites' supported browser list" which often still includes IE 8.

**Comment by niallobrien** [comment]
@ljharb https://support.microsoft.com/en-us/lifecycle/search?sort=PN&alpha=internet%20explorer
```
Beginning January 12, 2016, only the most current version of Internet Explorer available for a supported operating system will receive technical support and security updates.
```

**Comment by ljharb** [comment]
@niallobrien official support of a browser is entirely unrelated to sites supporting a browser - the latter depends on actual usage. Hopefully the former will decrease actual usage, of course, but history hasn't proven that to be a foregone conclusion.

**Comment by niallobrien** [comment]
I'd argue that most using this module wouldn't be targeting < IE910.

**Comment by ljharb** [comment]
I don't know how you could possibly make that claim one way or another.

**Comment by ljharb** [comment]
1% of a billion people is still way too many. I'm not going to have this debate here as it's irrelevant. The UI/UX experience of these is subpar, even in modern browsers, unrelated to how they function from a JS perspective.
