### ISSUE TITLE
Generate an edit form

### ISSUE THREAD

**Issue by vpontis** [caolan/forms#136]
How should I modify my code so that the value of each field is inserted? I want to make an edit form for a specific model. I've been playing around with `form.bind` but that hasn't quite done it.

**Comment by krloslao** [comment]
hello, im trying to do the same but with a user data like 

login: fields.string({ value: #{user.login})

or something like this, but this does not work, need help. thanks in advance :)

**Comment by ljharb** [comment]
@krloslao what's `#{user.login}`? that isn't valid JS syntax.

**Comment by krloslao** [comment]
Sorry, i already fix my trouble. Thanks for answer.
