### ISSUE TITLE
Default Field Values

### ISSUE THREAD

**Issue by rdegges** [caolan/forms#155]
It would be awesome to be able to specify default values for fields.

I find myself creating a lot of forms where I have optional fields, but if a user doesn't supply a value for an option field I'd like to populate it manually with a default value.

It would save me a lot of code if this library supported something of this sort out of the box.

**Comment by ljharb** [comment]
Duplicate of #120 which has a number of ideas in it - namely, binding prior to rendering.

I'm open to better ideas of how to do this, but it seems like "binding before rendering" would solve this.

Please reopen if not.
