### ISSUE TITLE
Extending the set of widgets without editing the module

### ISSUE THREAD

**Issue by Cyberuben** [caolan/forms#158]
I haven't been able to find a way to add widgets without having to copy paste functions from the original module or editing the widgets.js file.

**Comment by ljharb** [comment]
A widget is simply a function that takes in options, and returns an object. Here's an example custom widget:
```js
var email = require('forms/lib/widgets/email');
function customWidget(options) {
  var w = email(options);
  var originalHTML = w.toHTML;
  w.toHTML = function (name, f) {
    var html = originalHTML(name, f);
    return html + '<span>custom</span>';
  };
  return w;
}
```
