### ISSUE TITLE
validators.required blocked

### ISSUE THREAD

**Issue by zxcware** [caolan/forms#159]
Hi,

I am looking for an approach to trim the request data and check empty after that. By navigating the code base, I found 'validators.required'. However, it blocks on checking and freezes the nodejs server process. Any clue why?

I hope we could add a feature to store and validate the trimed data.

Thanks,
Zhixiong

**Comment by ljharb** [comment]
I'm not sure what you mean by "blocks" - https://github.com/caolan/forms/blob/master/lib/validators.js#L64-L73 doesn't block on anything.

Can you provide a code sample of how you're using `forms`?

**Comment by zxcware** [comment]
Hi ljharb, 

Below is the sample code:
```javascript
var loginForm = forms.create({
  email: fields.email({
    required: true,
    validators: [validators.required]
  }),
  password: fields.password({required: true})
});

app.post('/api/v1/login', function(request, response){
  loginForm.handle(request, {
    success: function(form){
      var login = form.data;
      getProfile(login.email, login.password, function(error, result){
        console.log('Error: getProfile() '.red, error)
        response.json({status: '500'});
      }, function(result){
        var profile = JSON.parse(result[0].detail);
        response.json({"profile": profile});
      });
    },
    error: function(form){
      response.json({status: 404, "errors": utils.extractFormErrors(form)});
    },
    empty: function(form){
      response.json({status: 404});
    }
  });
});
```
I sent a request with data{"email":"a@b.c", "password":"123"}. The server some how got blocked after calling loginForm.handle. 

What does the trim() function do in validators.js? Does it work similar to string.trim()?

I tried to add a new validator function serving the purpose of string.trim(). The same code is below. I could see 'new' successfully printed but the server got blocked after that.
```javascript
exports.nonEmpty = function (message) {
    console.log("new");
    if (!message) { message = '%s is required.'; }
    return function (form, field, callback) {
        if (field.data.trim().length === 0) {
            callbk(format(message, formatFieldName(field)));
        } else {
            callback();
        }
    };
};
```

Please let me know if you need other information. Thanks!Hi ljharb, 

Below is the sample code:
```javascript
var loginForm = forms.create({
  email: fields.email({
    required: true,
    validators: [validators.required]
  }),
  password: fields.password({required: true})
});

app.post('/api/v1/login', function(request, response){
  loginForm.handle(request, {
    success: function(form){
      var login = form.data;
      getProfile(login.email, login.password, function(error, result){
        console.log('Error: getProfile() '.red, error)
        response.json({status: '500'});
      }, function(result){
        var profile = JSON.parse(result[0].detail);
        response.json({"profile": profile});
      });
    },
    error: function(form){
      response.json({status: 404, "errors": utils.extractFormErrors(form)});
    },
    empty: function(form){
      response.json({status: 404});
    }
  });
});
```
I sent a request with data{"email":"a@b.c", "password":"123"}. The server some how got blocked after calling loginForm.handle. 

What does the trim() function do in validators.js? Does it work similar to string.trim()?

I tried to add a new validator function serving the purpose of string.trim(). The same code is below. I could see 'new' successfully printed but the server got blocked after that.
```javascript
exports.nonEmpty = function (message) {
    console.log("new");
    if (!message) { message = '%s is required.'; }
    return function (form, field, callback) {
        if (field.data.trim().length === 0) {
            callbk(format(message, formatFieldName(field)));
        } else {
            callback();
        }
    };
};
```

Please let me know if you need other information. Thanks!

**Comment by ljharb** [comment]
The `trim` function is because the builtin `String#trim` is broken for many whitespace characters. In your last example, you're calling `callbk` not `callback` - that would definitely prevent the request from finishing - but I don't see anything wrong with your first example.

I do see that you're using a module that modifies `String.prototype` to provide the `.red` property - I *strongly* suggest using a module that does not do this, as that absolutely might cause problems.

However, I think this issue is caused by using `validators: [validators.required]` - try `validators: [validators.required('a message to display when the required item is not present')]` instead.
