### ISSUE TITLE
Bootstrap compatible output - push form-control?

### ISSUE THREAD

**Issue by nova76** [caolan/forms#163]
object.widget.classes.push('form-control');
   change(?):
    if (object.widget.classes.indexOf('form-control')==-1)
    {	
    	object.widget.classes.push('form-control');
    }

**Comment by ljharb** [comment]
I'm not really sure what your question is - duplicate CSS classes aren't problematic, and this code merely prevents a duplicate "form-control" CSS class from being applied. Is this causing you a problem?

**Comment by nova76** [comment]
Yes, duplicate once OK. But all page download will generate new one. For example 30 page download 30x "form-control" CSS class in one field.

**Comment by ljharb** [comment]
Ah, thanks, that's much clearer. I'll take a look at this, thanks.
