### ISSUE TITLE
Required nested field is not enforced.

### ISSUE THREAD

**Issue by yaru22** [caolan/forms#165]
I expect the following to fail because the nested fields (`first` and `last`) are not present. However, it validates. Is this a bug or an intended behaviour?

```js
import forms, { fields, validators } from 'forms';

const nestedForm = forms.create({
  name: {
    first: fields.string({ required: validators.required('first') }),
    last: fields.string({ required: validators.required('last') }),
  },
});

const handlers = {
  success(form) {
    console.log('success');
  },

  other(form) {
    console.log('fail');
  },
};

nestedForm.handle({ notRequired: true }, handlers);
// console -> success
```

Thanks.

**Comment by ljharb** [comment]
This is a tricky one. Your expectation is entirely sensible, and it should work like that.

However, the way nested object fields are handled right now is as an actual nested form. I'll have to think about how to resolve this.
