### ISSUE TITLE
Any example of how to make a select field?

### ISSUE THREAD

**Issue by ivanquirino** [caolan/forms#171]
I can't see on the docs how do I make a select field. I want a select field that shows "bronze", "silver, "gold", but actual values are 1, 2, 3.

**Comment by ljharb** [comment]
`select` widgets take a "choices" object, whose keys are the `<option>` values, and whose values are the `<option>` HTML content.

**Comment by ivanquirino** [comment]
like this? 
```javascript
options.widget = widgets.select({choices: {'1':'bronze'. '2':'silver', '3':'gold'}});
fields.string(options);
```

**Comment by ivanquirino** [comment]
I tested here and actually is not the widget that take the choices object, but the field. You passo the choices object with the field options.

**Comment by ljharb** [comment]
Ah right thanks :-) clearly the documentation needs improvement, for which a PR is welcome!

**Comment by ivanquirino** [comment]
I would like, but I've been very busy ATM, coding both web and Android.on a project for the company. My head gets confused sometimes, creating new objects in Java using {}.
