### ISSUE TITLE
Verify dynamical added Fields via JS

### ISSUE THREAD

**Issue by racol66** [caolan/forms#174]
Hi, 

I've created a form to edit select attribute element (=select data with dynamical option; 1 to N): so, the user can add options when he clicks on an "added value option" button. 

In JS (public), I added  a new row witch contains form fields for the new option (as example :  <label>New Option X</label><input type="text" name="options[X][code]" /><input type="text" name="options[X][value]" />). 

When I submit the form, the server form doesn't know my new dynamical fields, but only those I've created during declaration the form in server side (before form render). 

That's normal, but how could I check a dynamical field added to the form in public side and unknown from server side without Ajax called by field ?

My problem is, for the moment, "I add form data to mongodb if the form verification is correct, I'll added it : 

<label>New Option X</label><input type="text" name="options[X][code]" /><input type="text" name="options[X][value]" />

<label>New Option By HACKER</label><input type="text" name="options[By HACKER][code]" /><input type="text" name="options[By HACKER][value]" />

But, as you can see, for the second record, an hacker hacks my form but pass through verification because the first verification is passed well.

How can I add forms fields in front side via JS dynamicaly (JQUERY) and ensure a good form verification via caolan/forms ? 

Thanks in advance !

Raph

**Comment by ljharb** [comment]
You can't, unless you also add the fields on the serverside - since the server has no way of knowing what you did dynamically.

The primary use case for `forms` involves creating 100% of the final form on the server, and not altering it on the client - so you can use the same form object on both client and server for validation.

**Comment by Raphael-johanne** [comment]
Hi !

And thank you for your answer !

Most of the time, when I must create a form for a client, it must be dynamical as I said in my example. It could be interesting to do a widget to verify some pieces of fields like :
`
<label>Child 1</label>
<input type="text" name="wrapper['children'][1][age]" />

<label>Child 2</label>
<input type="text" name="wrapper['children'][2][age]" />
`
With server side form field with wrapper type; not verified if does not exist in submitted data and not mandatory, but required and verify if there are.

Without to call server via Ajax or create a dynamical form from server side; just said, "that's cool, you can create a new form field for your child, but if you create it, you must complete his age." 

Raph

**Comment by ljharb** [comment]
If you want to use `forms` to validate this use case, you need to have a way for the server to know which fields it needs to add prior to `.bind`ing and validating. There's no way around the fact that if the browser has knowledge the server doesn't, the server can't validate the request.

**Comment by Raphael-johanne** [comment]
Hi !

And thank you for your answer !

Mh, not agreed,  we can told via server side : "this field can have 0 to n values,  if submitted, we must verify if ages and firstnames are not empty; it was my proposition via a wrapper widget for dynamical fields.

As example : 
`
var wrapperChildren = fields.string({name: 'children', widget : widgets.wrapper(), fields :
 age          : fields.string({required : true, label : "Age"}),
 firstname : fields.string({required : true, label : "Firstname"})
});
`
The server can receive an array of children information and can verify it 

_children_ name is posted, it is a wrapper of 0 to n fields, I know the fields value to verify (age and firstname for each one). If I haven't those fields, failed, go to the next. Next match to verification (wrapper[1][age] = 18 && wrapper[1][firstname] = bob), etc. 

So the form is initialized from server side, but client can propose 0 to n submit for a field with a correct server side verification.

what do you think ?

Raph
