### ISSUE TITLE
id_undefined when using widget.toHTML()

### ISSUE THREAD

**Issue by ryanannatuvasquez** [caolan/forms#175]
Hi team I have form like this

```js
var form = forms.create({
    fullname: fields.string({
        required: true,
        id: "test_id" // with or without this
     })
});
```

but when i try to access widget and use `toHTML()` function it gives me the widget and the id is `id_undefined`

```js
console.log(form.fields.fullname.widget.toHTML());
// result: <input type="text" id="id_undefined" />
```

any fix for this?

**Comment by ljharb** [comment]
First, you need to specify a "name" for any input, otherwise it won't be submitted.

However, the real issue is that you need to specify `attrs: { id: 'test_id' }`.

**Comment by ryanannatuvasquez** [comment]
Thanks! I get it to work if I passed the name

```js
console.log(form.fields.fullname.widget.toHTML(name));
```
