### ISSUE TITLE
Arrays in form body

### ISSUE THREAD

**Issue by kwafarkye** [caolan/forms#181]
When calling form.handle inside a POST route, the form.data object passed to the success callback function sets the array field as a string joined with commas. Using express with bodyParser middleware

Here is an example:
`console.log(req.body.arr); // [ 'a', 'b', 'c' ]`
`form.handle(req, {  success: function (form) { console.log(form.data.arr); // 'a,b,c' } });`

**Comment by ljharb** [comment]
Can you share the code that you use to construct your `form` object?

**Comment by kwafarkye** [comment]
Here's code block to generate form, render the view, and the POST route to handle incoming form data (using express 4 and body-parser middleware):
<pre><code>
var forms = require('forms');
var fields = forms.fields;
var widgets = forms.widgets;

function bsField (type, options) {
    options = options || {};
    switch (type) {
        case 'multipleSelect':
        return fields.string({
            required: options.required,
            label: options.label,
            id: options.id,
            widget: widgets.multipleSelect({ classes: ['form-control'] }),
            choices: options.choices,
            cssClasses: {
                label: ['control-label']
            }
        });
   }
}

var helpChoices = {
   'Math': 'Math',
   'English': 'English',
   'Physics': 'Physics',
   'Chemistry': 'Chemistry',
   'Science (Physics, Chemistry)': 'Science (Physics, Chemistry)'
};

var formProps = {
   help_list: bsField('multiselect', { id: 'help_list_select', label: 'Help List', choices: helpChoices })
}

var userForm = forms.create(formProps);

var withBootstrap = function (name, object) {
    if (!Array.isArray(object.widget.classes)) { object.widget.classes = []; }

    // Only add form-control to widget objects that are not multipleCheckbox
    if (object.widget && object.widget.type !== 'multipleCheckbox') {
        if (object.widget.classes.indexOf('form-control') === -1) {
            object.widget.classes.push('form-control');
        }
    }

    var label = object.labelHTML(name);
    var error = object.error ? '&lt;div class="alert alert-error help-block"&gt;' + object.error + '&lt;/div&gt;' : '' ;

    var validationclass = object.value && !object.error ? 'has-success' : '';
    validationclass = object.error ? 'has-error' : validationclass;

    var widget = object.widget.toHTML(name, object);
    return '&lt;div class="form-group ' + validationclass + '"&gt;' + label + widget + error + '&lt;/div&gt;';
};

// Route to edit User (renders view)
router.get('/edit', function (req, res, next) {
   var user = { id: '123', name: 'hello', help_list: [] };
   return res.render('edit.html', { user: user, formHtml: userForm.toHTML(withBootstrap) });
});

// Route that handles POST of form data
router.post('/edit', function (req, res) {
   var target_form = userForm;
   target_form.handle(req, {
      success: function (f) {
         console.log(f.data.help_list); // Should receive array here, get string instead
         return res.render('index.html');
      }
   });
});

</code></pre>

Here's the form in edit.html:
<pre><code>&lt;form class="form-horizontal col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2" method="POST"&gt;
    &lt;div class="form_group"&gt;
    &lt;label for="id_help_list" class="control-label"&gt;Help List&lt;/label&gt;
        &lt;select multiple="multiple" name="help_list" id="help_list_select" class="form-control"&gt;
            &lt;option value="Math"&gt;Math&lt;/option&gt;
            &lt;option value="English"&gt;English&lt;/option&gt;
            &lt;option value="Physics"&gt;Physics&lt;/option&gt;
            &lt;option value="Chemistry"&gt;Chemistry&lt;/option&gt;
            &lt;option value="Science (Physics, Chemistry)"&gt;Science (Physics, Chemistry)&lt;/option&gt;
        &lt;select&gt;
    &lt;/div&gt;
    &lt;button type="submit" class="btn btn-default pull-right"&gt;Save&lt;/button&gt;
&lt;/form&gt;</code></pre>

When I access the edit.html page and select the following in the #help_list_select multiselect box:
Physics
Chemistry
Science (Physics, Chemistry)

I submit the form to POST /edit, and the `console.log(f.data.help_list);` returns the following:
Physics,Chemistry,Science (Physics, Chemistry)

I expected it to return:
[ 'Physics', 'Chemistry', 'Science (Physics, Chemistry)' ]

**Comment by ljharb** [comment]
Why are you using `fields.string` for multiple values? What happens if you use `fields.array` instead?

**Comment by kwafarkye** [comment]
@ljharb That did the trick. Silly mistake on my end, thanks for the help!
