### ISSUE TITLE
Bound form does not have form.handle

### ISSUE THREAD

**Issue by SHBelsky** [caolan/forms#193]
I'm trying to use two independent forms with the same options, and I'm having problems using `form.handle()` on the newly bound form object. If I do this:

`var form2 = form1.bind(data);`

The form works just fine. But calling `form2.handle()` on the new form returns an error saying the function is undefined. Doing a `console.log` on `form2` does indicate that `handle` is missing. The documentation says that newly bound form objects should have all properties of the parent form object, but this isn't the case.

I'm aware that since the form options are the same, I could just validate the data using the same form and two different data sets. I'd just like to have the two separated if at all possible, versus having this overlap.

**Comment by ljharb** [comment]
A bound form also doesn't have a `.bind` method - both `.bind` and `.handle` do binding, and once bound, a form can't be rebound - the intention is that you keep the unbound form and reuse *that* across requests - creating a new bound instance on every request.

**Comment by SHBelsky** [comment]
Gotcha. The documentation was misleading when it said that newly bound form objects inherited all their parent form's properties. Thanks!

**Comment by ljharb** [comment]
A pull request to clear that up would be appreciated :-) (also tho, properties, not methods)
