### ISSUE TITLE
Tags are not properly accessible through forms

### ISSUE THREAD

**Issue by SHBelsky** [caolan/forms#194]
I'm trying to use the `tag` feature in order to separate content in my forms. However, it does not appear to be exposed through the `forms` variable (`require("forms")`). `console.log(require("forms"))` indicates that there is no `tag` property that would allow me to use any of its functions. There isn't any documentation to indicate how I am otherwise supposed to use the tags; I'm just going off of what I've found when looking in the tests. How should I actually call the tag function?

**Comment by ljharb** [comment]
Correct, it's not exposed on the main entry point.

You can do `require('forms/lib/tag')`, but it's not really intended to be consumed outside the module.

**Comment by SHBelsky** [comment]
I suppose my followup question is this: Is there a way to implement section headers or separators for different parts of the same form? The tag functionality didn't work as I thought it might, since it's treated as a form element and not a separate entity. Is there a better way to natively create just a plain div in the middle of different inputs?

**Comment by voxpelli** [comment]
I achieved such a div through a custom HTML field/widget, only way to do it I think.

Would like to wrap up all of the custom fields I've created at work and make a PR of it so that we can improve the workflow for creating custom fields and widgets, but so far unfortunately haven't had time yet. Is that something that would be of interest?

**Comment by SHBelsky** [comment]
That would be great, or at least a PR to show how you would create such a widget. I'm at a loss as to how to do it.

**Comment by ljharb** [comment]
Yes, a custom widget would do it.

@voxpelli As far as PRring custom fields into this module, that would depend on the specific module. I'm happy to review a PR but I can't promise any of them would make it in without reviewing them first.

**Comment by SHBelsky** [comment]
@voxpelli Were you ever able to do a PR? Or could you post your code for the widget here? :)

**Comment by SHBelsky** [comment]
Sort of a hacky way of doing this, but it's better than nothing. I created a `label` widget that did not correspond to any other input element, and supplied the content I wanted.

    Test_Tag: widgets.label({
        classes: ["form-section-header"],
        content: "User Information"
    }),

From there, you can customize the appearance of the header however you want with the `form-section-header` CSS class. This is effectively what I needed. :)

**Comment by voxpelli** [comment]
I finally got this released as the `html` field here: https://github.com/Sydsvenskan/node-forms-utils#fields
