### ISSUE TITLE
Is it possible to add an HTML markup element?

### ISSUE THREAD

**Issue by davidwhthomas** [caolan/forms#195]
Is it possible to add an HTML markup element?
For example, between two form elements, there might be some generic intro text or HTML.
e.g:

1. Label: input element
2. Generic text/html
3. Label: input element

Can such text be added as an element to the form, without requiring any input element?

**Comment by ljharb** [comment]
You'd either need to build up the form HTML manually, widget by widget, or, modify one of the widgets to prepend or append your desired HTML.

**Comment by davidwhthomas** [comment]
Thanks, I added a basic widget for a markup element. 
```
exports.markup = function (options) {
    var opt = options || {tag: 'div', escape: true};
    var w = {
        classes: opt.classes,
        tag: opt.tag
    };
    var userAttrs = getUserAttrs(opt);
    w.toHTML = function (name, field) {
        var f = field || {};
        var attrs = {
            name: name,
            id: f.id === false ? false : (f.id || true),
            classes: w.classes
        };
        return tag(opt.tag, [attrs, userAttrs, w.attrs || {}], opt.value || '', opt.escape === false);
    };
    return w;
};
```
It can be used, with optional HTML content escape encoding, in form.create as follows:
```
markup: fields.string({
  widget: widgets.markup({
    escape: false,
    tag: 'div',
    value: 'This is the extended <strong>content</strong> here.'
  })
}),
```
Would need a bit of tuning, still adds the label, but may serve as a starter for others looking.

Cheers,
David
