### ISSUE TITLE
Wrong POST for multipleCheckbox?

### ISSUE THREAD

**Issue by oviboy** [caolan/forms#199]
I'm trying the complex test simplified with:
```
var complexForm = forms.create({
     more_options: fields.array({
         label: "test",
         choices: { 0:'item 1', 1:'item 2' },
         widget: widgets.multipleCheckbox()
     })
 });
```
However, after POST, I get:

> { more_options: [ '1' ] }

I was expecting more_options to be [ '1', '2' ] because I've checked both Check boxes.
I'm I doing something wrong with this example ?

**Comment by ljharb** [comment]
Some servers will interpret `more_options=1&more_options=2` as either the final item (`2`), or as an array of both (`[1, 2]`).

However, all servers will interpret `more_options[]=1&more_options[]=2` as either the final item (`2`), or as an array of both (`[1, 2]`).

Thus, the solution is:
```js
var complexForm = forms.create({
     'more_options[]': fields.array({
         label: "test",
         choices: { 0:'item 1', 1:'item 2' },
         widget: widgets.multipleCheckbox()
     })
 });
```

**Comment by nervgh** [comment]
@ljharb 
```js
var complexForm = forms.create({
     'more_options[]': fields.array({
         label: "test",
         choices: { 0:'item 1', 1:'item 2' },
         widget: widgets.multipleCheckbox()
     })
 });
```
It does not work for editing. My use case is:

```js
exports.get = {
  // works as ecspected here
  'add': async function(ctx) {
    let form = await getFrom()
    ctx.state.form = form
    ctx.render('', 'views/admin/default/add')
  },
  // doesn't work because 
    // 1) the model has `more_options` field 
    // 2) but the form has `more_options[]` field
  'edit/:id': async function(ctx) {
    let item = await Model.findById(ctx.params.id)
    let form = await getFrom()
    ctx.state.form = form.bind(item)
    ctx.render('', 'views/admin/default/edit')
  }
}
```

**Comment by ljharb** [comment]
If your model doesn't match your form inputs, then you need to bind to a different object. Model fields aren't supposed to exactly match http query string field names.
