### ISSUE TITLE
Form with only boolean fields does not validate successfully

### ISSUE THREAD

**Issue by net147** [caolan/forms#205]
If a form has only optional boolean fields, the "other" handler is called instead of the "success" handler when all the boxes are unchecked.

**Comment by ljharb** [comment]
Thanks, can you provide a test case (code)?

**Comment by ljharb** [comment]
Specifically, I think this is because of the way browser forms work. If a checkbox is unchecked, nothing is submitted - checkboxes always have to be paired after a hidden input with the "off" value so you can get a reliable signal that the box was unchecked.
