### ISSUE TITLE
build broken due to ecstatic?

### ISSUE THREAD

**Issue by alberanid** [caolan/forms#208]
We are building **forms** 1.3.0 on a Yocto environment, and the dependency tree ends up including **ecstatic** ~0.4.5, which was removed from the npm repository, few days ago.

Is **forms** 1.3.0 broken for everyone? Any idea how to fix this?

Thanks!

**Comment by ljharb** [comment]
It seems like it's coming in from `testling` which is a dev dep - why are you "building" forms and not using it from npm? It's just JS.

**Comment by alberanid** [comment]
@ljharb that's correct, I already opened an issue for testling: https://github.com/substack/testling/issues/118

We are building it because Yocto ( https://www.yoctoproject.org/ ) is a framework to build complete Linux distributions, so everything is built from the upstream sources plus patches, if needed.

I guess we'll find a way to remove the dependency, on Monday.

Thanks for your help.

**Comment by ljharb** [comment]
@alberanid since it's a dev dep, you should be running `npm install --production` so it's not installed in the first place, thereby bypassing this issue (and probably massively shrinking the size of your distribution)
