### ISSUE TITLE
Strange solutions

### ISSUE THREAD

**Issue by WinterSilence** [caolan/forms#213]
Good solution and strange code, as example:
~~~js
toHTML: function () {
     var form = this;
     var iterator = arguments.length > 1 ? arguments[1] : arguments[0];
     var name = arguments.length > 1 ? arguments[0] : void 0;
~~~
it's maximal not IDE frendly, I dont have any idea why parameters not defined.

**Comment by WinterSilence** [comment]
not cross html solutions, as example:
~~~
return '<' + safeTagName + attrsHTML + (isSelfClosing(safeTagName) ? ' />' : '>' + safeContent + '</' + safeTagName + '>');
~~~
html5 dont use slash at end to single tags

**Comment by ljharb** [comment]
a) IDE-friendly is irrelevant; many people don't use an IDE at all, myself included.
b) the arguments are optional and variadic, and defining them would make the code less readable, and make the function's `length` be wrong
c) HTML5 does not *require* the closing slash, but it does allow it, and it's required in XHTML, so "always including the closing slash" is a better practice.

Generally speaking, offering an unsolicited code review of code you don't maintain (and perhaps don't fully understand) is considered rude and hostile. I'm going to close this for now, but if you have any issues to report or concrete PRs to file, please do so.
