### ISSUE TITLE
Add a Promise API side-by-side with the callback API of .validate()

### ISSUE THREAD

**Issue by voxpelli** [caolan/forms#217]
Both `form.validate()` and `field.validate()` is callback based and would make sense that they get the same treatment as `form.handle()` did in #215 

Both of the `validate()` methods revolves entirely around the `async` module:

https://github.com/caolan/forms/blob/4b99dfaaf16edfb925cefa35fd5861d133566d1e/lib/forms.js#L50-L61

I would therefore suggest that in creating this we do something like:

```javascript
const PonyPromise = typeof Promise === 'function' ? Promise : require('es6-promise').Promise;
```

And then uses `PonyPromise` instead of the `async` module.

That way the promise version of the `validate()` method can simply return the actual promise used within `forms` rather than mapping the result of the `async` module to a promise + all users who have native promises can just skip loading an extra module all together.

A possible extra that we could do is to allow Promises to be returned in all environments, no matter if they have native promises or not, but that wouldn't be the point, the point would be to avoid loading a module that isn't necessary.

**Comment by ljharb** [comment]
(ftr, the term "ponyfill" is absurd and unprofessional. i tend to use "polyfill" to mean that, and "shim" to mean a self-installing polyfill)

It's been a best practice for many years to never ship a Promise polyfill, and to instead require the user to provide one.

If the use of the async module can be trivially removed at all, then we can and should remove it - but if it can't be, then Promises wouldn't be an alternative to it.

The way bundling works, lazy requires break things. A library that might be needed must be loaded every time.

**Comment by voxpelli** [comment]
Right, lets keep `async` then as a helper and just do what #215 did for `handle()`
