### ISSUE TITLE
GHSL-2020-356: seeking security contact for your project

### ISSUE THREAD

**Issue by anticomputer** [caolan/forms#220]
The GitHub Security Lab reported a potential security vulnerability (GHSL-2020-356) in your project (caolan/forms). We are approaching 90 days since our initial report and as per our [coordinated disclosure policy](https://securitylab.github.com/advisories#policy), we intend to publish a public advisory detailing this issue. If you wish to discuss or further coordinate a response to this issue with the GitHub Security Lab, please contact us at securitylab@github.com within the next 7 days in reference to GHSL-2020-356 and we would love to help you resolve these issues. If not, feel free to close this issue and we will proceed with advisory publication on expiration.

**Comment by ljharb** [comment]
Usually the 90 days is meant to give _the maintainers_ time to address the issue, and I've had no report since.

I'll email you right now.

**Comment by anticomputer** [comment]
> Usually the 90 days is meant to give _the maintainers_ time to address the
> issue, and I've had no report before this.
>
> I'll email you right now.
>

We have redelivered the report to your preferred contact, the original report was delivered to: caolan@caolan.uk on dec 22, 2020.
